# Generated by Django 5.2.17 on 2026-09-15 04:52

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=120)),
                ('static_path', models.CharField(default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Documento del CV',
                'verbose_name_plural': 'Documentos del CV',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=120)),
                ('headline', models.CharField(default='', max_length=160)),
                ('tagline', models.CharField(default='', max_length=160)),
                ('hero_description', models.TextField(default='')),
                ('about', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('location', models.CharField(default='', max_length=200)),
                ('linkedin_url', models.URLField(default='')),
                ('github_url', models.URLField(default='')),
                ('page_title', models.CharField(default='', max_length=200)),
                ('meta_description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('kind', models.CharField(choices=[('carrera', 'Carrera'), ('bootcamp', 'Bootcamp'), ('curso', 'Curso')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Formación',
                'verbose_name_plural': 'Formaciones',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['carrera', 'bootcamp', 'curso'])), name='education_kind_valido')],
            },
            bases=(cv.models.PeriodDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('technologies', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(choices=[('web', 'Desarrollo web'), ('qa', 'QA / Testing'), ('education', 'Formación académica'), ('other', 'Otro')], max_length=50)),
                ('github_url', models.URLField(blank=True, default='')),
                ('demo_url', models.URLField(blank=True, default='')),
                ('published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['web', 'qa', 'education', 'other'])), name='project_category_valido')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('kind', models.CharField(choices=[('herramienta', 'Herramienta'), ('tecnica', 'Técnica')], max_length=20)),
                ('area', models.CharField(choices=[('qa', 'QA / Testing'), ('it', 'IT / Soporte'), ('desarrollo', 'Desarrollo'), ('gestion', 'Gestión / Versionado')], max_length=20)),
                ('level', models.CharField(choices=[('trabajo', 'Trabajo'), ('proyectos', 'Proyectos'), ('formacion', 'Formación')], max_length=20)),
                ('group', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['area', 'group', 'order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='skill_name_unico'), models.CheckConstraint(condition=models.Q(('kind__in', ['herramienta', 'tecnica'])), name='skill_kind_valido'), models.CheckConstraint(condition=models.Q(('area__in', ['qa', 'it', 'desarrollo', 'gestion'])), name='skill_area_valido'), models.CheckConstraint(condition=models.Q(('level__in', ['trabajo', 'proyectos', 'formacion'])), name='skill_level_valido')],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('area', models.CharField(choices=[('qa', 'QA / Testing'), ('it', 'IT / Soporte'), ('desarrollo', 'Desarrollo'), ('otro', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('responsibilities', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('skills', models.ManyToManyField(blank=True, related_name='experiences', to='cv.skill')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('area__in', ['qa', 'it', 'desarrollo', 'otro'])), name='experience_area_valido')],
            },
            bases=(cv.models.PeriodDisplayMixin, models.Model),
        ),
    ]
